#!/bin/bash

# System Variables
user=$(whoami)
hostname=$(hostname | sed 's/.local//g')
version="OS X $(sw_vers -productVersion)"
kernel="XNU"
uptime=$(uptime | sed 's/.*up \([^,]*\), .*/\1/')
shell="$SHELL"
terminal="$TERM"
#brewpackages="`brew list -l | wc -l | awk '{print $1 }'`"
#macportpackages="`port installed | wc -l | awk '{print $1 }'`"
cpu=$(sysctl -n machdep.cpu.brand_string)

# removes (R) and (TM) from the CPU name so it fits in a standard 80 window

cpu=$(echo "$cpu" | awk '$1=$1' | sed 's/([A-Z]\{1,2\})//g')

# if hostname is >35 characters, truncates to make it fit on std. 80 window
if [ ${#hostname} > 35 ]; then
   hostname=${hostname:0:35}
   # hostname=${hostname:(-35)} truncate from end/beginning
fi

mem=$(sysctl -n hw.memsize)
ram="$((mem/1000000000)) GB"
disk=`df | head -2 | tail -1 | awk '{print $5}'`

# Colors Variables
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

textColor=$(tput setaf $lightblue)
normal=$(tput sgr0)

# Package Manager (Homebrew or Macports)
packagehandler=$macportpackages

# Add a -c option to enable classic color logo
if [[ $1 == "-c" ]] || [[ $1 == "--color" ]]; then
  GREEN='\033[00;32m'
  YELLOW='\033[00;33m'
  LRED='\033[01;31m'
  RED='\033[00;31m'
  PURPLE='\033[00;35m'
  CYAN='\033[00;36m'
  BLUE='\033[00;34m'
fi

userText="${textColor}User:${normal}"
hostnameText="${textColor}Hostname:${normal}"
versionText="${textColor}Version:${normal}"
kernelText="${textColor}Kernel:${normal}"
uptimeText="${textColor}Uptime:${normal}"
shellText="${textColor}Shell:${normal}"
terminalText="${BLUE}${textColor}Terminal:${normal}"
packagehandlerText="${textColor}Packages:${normal}"
cpuText="${textColor}CPU:${normal}"
memoryText="${textColor}Memory:${normal}"
diskText="${textColor}Disk:${normal}"

echo -e "

${GREEN}                     ,
${GREEN}                  ,##; 
${GREEN}                 ####             $userText $user
${GREEN}                ;#\"               $hostnameText $hostname
${GREEN}       ,#####;,   ,;#####;,       $versionText $version
${GREEN}     ######################\"      $kernelText $kernel
${YELLOW}    #####################\"        $uptimeText $uptime
${YELLOW}    #####################         $shellText $shell
${LRED}    #####################         $terminalText $terminal
${RED}    ######################,       $packagehandlerText $packagehandler
${RED}     #######################      $cpuText $cpu
${PURPLE}      ####################\"       $memoryText $ram
${BLUE}        #################'        $diskText $disk
${BLUE}         \"####\"\"\"\"####\" ${normal}

"
