#!/bin/bash

# ==USER==
user=$(whoami)

# ==HOSTNAME==
hostname=$(hostname | sed 's/.local//g')
# if hostname is >35 characters, truncates to make it fit on std. 80 window
if [ ${#hostname} -gt 35 ]
then
   hostname=${hostname:0:35}
   # hostname=${hostname:(-35)} truncate from end/beginning
fi

# ==VERSION==
versionNumber=$(sw_vers -productVersion) # Finds version number

versionCalculation=${versionNumber:0:4}  # Cut sting to 1 decimal place for calculation
versionDecimal=$(echo "$versionCalculation * 10 - 100" | bc) # converts 10.9 > 9.0
versionInt=${versionDecimal%.*} # converts 9.0 => 9

declare -a versionsArray
versionsArray=( Cheetah Puma Jaguar Panther Tiger Leopard 
         Snow\ Leopard Lion Mountain\ Lion Mavericks )
		 
versionName=${versionsArray[versionInt]}

version="OS X $versionNumber $versionName"

# ==KERNEL==
kernel="XNU"

# ==UPTIME==
uptime=$(uptime | sed 's/.*up \([^,]*\), .*/\1/')

# ==SHELL==
shell="$SHELL"

# ==TERMINAL==
terminal="$TERM"

# ==PACKAGE MANAGER==
#brewpackages="`brew list -l | wc -l | awk '{print $1 }'`"
#macportpackages="`port installed | wc -l | awk '{print $1 }'`"
#packagehandler=$macportpackages

# ==CPU==
cpu=$(sysctl -n machdep.cpu.brand_string)
# removes (R) and (TM) from the CPU name so it fits in a standard 80 window
cpu=$(echo "$cpu" | awk '$1=$1' | sed 's/([A-Z]\{1,2\})//g')
 
# ==MEMORY==
mem=$(sysctl -n hw.memsize)
mem="$((mem/1000000000)) GB"

# ==DISK==
disk=`df | head -2 | tail -1 | awk '{print $5}'`

# Colors Variables
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

textColor=$(tput setaf $lightblue)
normal=$(tput sgr0)

# Add a -c option to enable classic color logo
if [[ $1 == "-c" ]] || [[ $1 == "--color" ]]; then
  GREEN='\033[00;32m'
  YELLOW='\033[00;33m'
  LRED='\033[01;31m'
  RED='\033[00;31m'
  PURPLE='\033[00;35m'
  CYAN='\033[00;36m'
  BLUE='\033[00;34m'
fi

userText="${textColor}User:${normal}"
hostnameText="${textColor}Hostname:${normal}"
versionText="${textColor}Version:${normal}"
kernelText="${textColor}Kernel:${normal}"
uptimeText="${textColor}Uptime:${normal}"
shellText="${textColor}Shell:${normal}"
terminalText="${BLUE}${textColor}Terminal:${normal}"
packagehandlerText="${textColor}Packages:${normal}"
cpuText="${textColor}CPU:${normal}"
memoryText="${textColor}Memory:${normal}"
diskText="${textColor}Disk:${normal}"

echo -e "

${GREEN}                     ,
${GREEN}                  ,##; 
${GREEN}                 ####             $userText $user
${GREEN}                ;#\"               $hostnameText $hostname
${GREEN}       ,#####;,   ,;#####;,       $versionText $version
${GREEN}     ######################\"      $kernelText $kernel
${YELLOW}    #####################\"        $uptimeText $uptime
${YELLOW}    #####################         $shellText $shell
${LRED}    #####################         $terminalText $terminal
${RED}    ######################,       $packagehandlerText
${RED}     #######################      $cpuText $cpu
${PURPLE}      ####################\"       $memoryText $mem
${BLUE}        #################'        $diskText $disk
${BLUE}         \"####\"\"\"\"####\" ${normal}

"
